//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class AIDiseaseDetectionDBEntities : DbContext
{
    public AIDiseaseDetectionDBEntities()
        : base("name=AIDiseaseDetectionDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblAdmin> tblAdmins { get; set; }
    public virtual DbSet<tblDisease> tblDiseases { get; set; }
    public virtual DbSet<tblfeature> tblfeatures { get; set; }
    public virtual DbSet<tblImage> tblImages { get; set; }
    public virtual DbSet<tblImageSegment> tblImageSegments { get; set; }
    public virtual DbSet<tblUser> tblUsers { get; set; }
    public virtual DbSet<tblUserType> tblUserTypes { get; set; }
    public virtual DbSet<tblReport> tblReports { get; set; }
    public virtual DbSet<tblimage2> tblimage2 { get; set; }
    public virtual DbSet<tblimage3> tblimage3 { get; set; }

    public virtual ObjectResult<AdminLogIn_Result> AdminLogIn(string email, string password)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("password", password) :
            new ObjectParameter("password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminLogIn_Result>("AdminLogIn", emailParameter, passwordParameter);
    }

    public virtual ObjectResult<UserLogIn_Result> UserLogIn(string email, string password)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("password", password) :
            new ObjectParameter("password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserLogIn_Result>("UserLogIn", emailParameter, passwordParameter);
    }
}
