//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblAdmin
{
    public int AdminID { get; set; }
    public string AdminName { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public int Contact_No { get; set; }
}

public partial class tblDisease
{
    public int DiseaseID { get; set; }
    public string DieaseName { get; set; }
}

public partial class tblfeature
{
    public int FeatureID { get; set; }
    public string FeatureName { get; set; }
    public int DieaseID { get; set; }
}

public partial class tblImage
{
    public int ImageID { get; set; }
    public string imageName { get; set; }
    public string ImagePath { get; set; }
    public string Image { get; set; }
}

public partial class tblimage2
{
    public int ImageID { get; set; }
    public byte[] Image { get; set; }
}

public partial class tblimage3
{
    public int imageID { get; set; }
    public byte[] image { get; set; }
}

public partial class tblImageSegment
{
    public int ImageSegmentID { get; set; }
    public string SegmentName { get; set; }
    public int DieaseID { get; set; }
}

public partial class tblReport
{
    public int ReportID { get; set; }
    public string Result { get; set; }
}

public partial class tblUser
{
    public int UserID { get; set; }
    public string UserName { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public int Age { get; set; }
    public string Gender { get; set; }
    public int ReportID { get; set; }
}

public partial class tblUserType
{
    public int UserTypeID { get; set; }
    public string TypeName { get; set; }
}

public partial class AdminLogIn_Result
{
    public int AdminID { get; set; }
    public string AdminName { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public int Contact_No { get; set; }
}

public partial class UserLogIn_Result
{
    public int UserID { get; set; }
    public string UserName { get; set; }
    public string EmailAddress { get; set; }
    public string Password { get; set; }
    public int Age { get; set; }
    public string Gender { get; set; }
    public int ReportID { get; set; }
}
